# Generated by Django 2.1.5 on 2019-02-21 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talk_type', models.CharField(max_length=20)),
                ('talk_name', models.CharField(max_length=20)),
                ('talk_age', models.IntegerField()),
                ('deviceID', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_info.Profile')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
