# Generated by Django 2.1.5 on 2019-02-21 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg1', models.TextField(blank=True, max_length=100, null=True)),
                ('msg2', models.TextField(blank=True, max_length=100, null=True)),
                ('msg3', models.TextField(blank=True, max_length=100, null=True)),
                ('msg4', models.TextField(blank=True, max_length=100, null=True)),
                ('msg5', models.TextField(blank=True, max_length=100, null=True)),
                ('msg6', models.TextField(blank=True, max_length=100, null=True)),
                ('msg7', models.TextField(blank=True, max_length=100, null=True)),
                ('msg8', models.TextField(blank=True, max_length=100, null=True)),
                ('msg9', models.TextField(blank=True, max_length=100, null=True)),
                ('msg10', models.TextField(blank=True, max_length=100, null=True)),
                ('img1', models.ImageField(blank=True, upload_to='')),
                ('img2', models.ImageField(blank=True, upload_to='')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_info.Profile')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
