# Generated by Django 2.1.5 on 2019-02-21 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
